"""Corpus determinism gate (issue #1930).

The golden corpus generator is built to be byte-deterministic: fixed
seeds, sorted iteration, and an explicit ``os.utime`` pass that pins
file mtimes to a constant epoch. This test guards that property in CI
so a regression in the generator (or a manually-edited fixture on
disk) fails the build instead of silently drifting.

What this catches:

* a generator-side change that flips RNG ordering, drops the mtime
  normalisation, or otherwise breaks reproducibility -- the
  regenerated bytes diverge from the committed bytes;
* a fixture-on-disk drift where the manifest still says X but the
  committed ``.tif`` was edited (or stale) so it no longer matches
  what the manifest would produce.

The test is fast (regenerating 30 small TIFFs is a few seconds) and
carries the ``fast`` tag in spirit: it is parameterised over every
manifest entry but each parameter is a single md5 compare, so the
whole module runs comfortably inside the PR fast lane. We do not
attach the ``slow`` pytest marker so ``pytest -m "not slow"`` keeps
it in scope.

Fixtures the manifest declares but that are not committed on disk
(today: ``example_tiled_uint16_deflate_pred2``, kept as a
schema-illustrating example) are skipped here rather than failing,
mirroring how the per-backend tests handle the same case.
"""
from __future__ import annotations

import hashlib
import pathlib

import pytest

# rasterio / pyyaml are runtime deps of the generator. importorskip
# keeps minimal environments green by skipping the whole module when
# either is missing.
pytest.importorskip("yaml")
pytest.importorskip("rasterio")

from xrspatial.geotiff.tests.golden_corpus import generate  # noqa: E402


FIXTURES_DIR = (
    pathlib.Path(__file__).resolve().parent / "fixtures"
)


def _md5(path: pathlib.Path) -> str:
    h = hashlib.md5()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def _manifest_ids() -> list[str]:
    """Return manifest fixture ids in sorted order (the generator's
    on-disk order)."""
    manifest = generate.load_manifest()
    entries = generate.validate(manifest)
    return sorted(e["id"] for e in entries)


@pytest.fixture(scope="module")
def regenerated_dir(tmp_path_factory: pytest.TempPathFactory) -> pathlib.Path:
    """Regenerate the entire corpus into a module-scoped tmp dir.

    Module-scoped so the (few-second) write cost is paid once per
    test session rather than per parametrised case.
    """
    out = tmp_path_factory.mktemp("regen_corpus_1930")
    generate.generate(output_dir=out)
    return out


@pytest.mark.parametrize("fixture_id", _manifest_ids())
def test_fixture_bytes_are_deterministic(
    fixture_id: str, regenerated_dir: pathlib.Path
) -> None:
    """The committed ``.tif`` for each manifest id matches what the
    generator would produce today, byte for byte.

    Skip rather than fail when the committed file is missing -- that
    means the fixture is declared but intentionally not shipped
    (e.g. the schema-illustrating example fixture). The per-backend
    tests handle this the same way.
    """
    committed = FIXTURES_DIR / f"{fixture_id}.tif"
    if not committed.exists():
        pytest.skip(
            f"fixture {fixture_id!r} is in the manifest but not committed "
            f"on disk; nothing to compare"
        )
    regenerated = regenerated_dir / f"{fixture_id}.tif"
    assert regenerated.exists(), (
        f"generator did not produce {fixture_id!r}; check the generator "
        f"and manifest stayed in sync"
    )
    committed_md5 = _md5(committed)
    regenerated_md5 = _md5(regenerated)
    assert committed_md5 == regenerated_md5, (
        f"fixture {fixture_id!r} drifted: committed md5 {committed_md5} "
        f"does not match regenerated md5 {regenerated_md5}. Either the "
        f"generator changed and the committed fixtures need re-running "
        f"(`python -m xrspatial.geotiff.tests.golden_corpus.generate`), "
        f"or the committed fixture was edited out of band."
    )


def test_external_overview_sidecar_is_deterministic(
    regenerated_dir: pathlib.Path,
) -> None:
    """Fixtures with ``external_overview: true`` ship a sidecar
    ``<id>.tif.ovr`` next to the main ``.tif``. The sidecar bytes are
    part of the determinism contract too.
    """
    sidecar_name = "overview_external_ovr_uint16.tif.ovr"
    committed = FIXTURES_DIR / sidecar_name
    if not committed.exists():
        pytest.skip(
            f"sidecar {sidecar_name!r} is not committed; nothing to compare"
        )
    regenerated = regenerated_dir / sidecar_name
    assert regenerated.exists(), (
        f"generator did not produce {sidecar_name!r}; external_overview "
        f"path may be broken"
    )
    assert _md5(committed) == _md5(regenerated), (
        f"{sidecar_name!r} drifted from the committed bytes; rerun the "
        f"generator and recommit, or revert the on-disk edit"
    )


def test_no_orphan_fixtures_on_disk() -> None:
    """Every committed ``.tif`` (and ``.tif.ovr`` sidecar) corresponds
    to a manifest entry. Catches stale fixtures left behind after a
    manifest delete.
    """
    manifest_ids = set(_manifest_ids())
    orphans: list[str] = []
    for path in sorted(FIXTURES_DIR.glob("*.tif")):
        if path.stem not in manifest_ids:
            orphans.append(path.name)
    for path in sorted(FIXTURES_DIR.glob("*.tif.ovr")):
        # sidecar stem: strip ``.tif`` to recover the fixture id
        fid = path.name[: -len(".tif.ovr")]
        if fid not in manifest_ids:
            orphans.append(path.name)
    assert not orphans, (
        f"committed fixtures {orphans!r} have no matching manifest entry; "
        f"either re-add them to the manifest or remove the orphan files"
    )
