{% set sdata = load_setup_py_data() %}
{% set version = sdata.get('version') %}

package:
  name: xarray-spatial
  version: {{ version.split('.post')[0] }}

source:
  path: ..
  
requirements:
  host:
    - python
    - setuptools >=46.4.0
    - pyct
    - param
  run:
    - python
    {% for dep in sdata.get('install_requires', {}) %}
    - {{ dep }}
    {% endfor %}

test:
  requires:
    - pytest >=2.8.5
     {% for dep in sdata['extras_require']['tests'] %}
     - {{ dep }}
     {% endfor %}
  imports:
    - xrspatial

about:
  home: https://github.com/makepath/xarray-spatial
  license: MIT
