
package:
  name: xarray-spatial
  version: 0.1.2

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - datashader

test:
  requires:
    - pytest >=2.8.5
  imports:
    - xrspatial

about:
  home: https://github.com/makepath/xarray-spatial
  license: MIT
