name: flake8 Lint

on: [push, pull_request]

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: Lint with flake8
    steps:
      - uses: actions/checkout@v1
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.3
        with:
          output: ''
      - uses: ricardochaves/python-lint@v1.3.0
        env:
          FILES: echo ${{ steps.file_changes.outputs.files_modified}} | grep -oP '(?=\s?)(\w*?\.py)(?=\s?)'
      - name: Test
        run: echo ${{ env.FILES }}
      - uses: ricardochaves/python-lint@v1.3.0
        with:
          python-root-list: ${FILES}
          use-pylint: false
          use-pycodestyle: false
          use-flake8: true
          use-black: false
          use-mypy: false
          use-isort: false
          extra-flake8-options: '--filename=*.py'